# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.4'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.2'
      - uses: webfactory/ssh-agent@4fcb25e
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Setup Julia registries"
        run: |
          julia -e 'using Pkg; pkg"registry add General"'
          julia -e 'using Pkg; pkg"registry add https://github.com/JuliaPOMDP/Registry"'
          julia -e 'using Pkg; pkg"registry add git@github.com:SmartMonitoringSchemes/Registry.git"'
      - name: "Setup dependencies"
        run: |
          R -e "install.packages('changepoint', repos = 'http://cran.us.r-project.org')"
          R -e "install.packages('changepoint.np', repos = 'http://cran.us.r-project.org')"
          pip install munkres scikit-learn
      - name: "Run Julia tests"
        run: |
          julia --project=. --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true);'
      - name: "Upload coverage"
        # Don't fail if the Codecov API times out.
        continue-on-error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(Codecov.process_folder())"
