name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.6'
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.2'
      - name: Setup registries
        run: |
          julia -e 'using Pkg; pkg"registry add General"'
          julia -e 'using Pkg; pkg"registry add https://github.com/JuliaPOMDP/Registry"'
          julia -e 'using Pkg; pkg"registry add https://github.com/SmartMonitoringSchemes/Registry"'
      - name: Setup dependencies
        run: |
          R -e "install.packages('changepoint', repos = 'http://cran.us.r-project.org')"
          R -e "install.packages('changepoint.np', repos = 'http://cran.us.r-project.org')"
          pip install munkres scikit-learn
      - name: Run tests
        # The first two lines are required to fix a segfault with R and RCall.
        run: |
          export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
          julia --project=. -e 'using Pkg; Pkg.instantiate(); using RCall'
          julia --project=. --check-bounds=yes -e 'using Pkg; Pkg.test(coverage=true);'
      - name: Upload coverage
        run: julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Codecov.submit(Codecov.process_folder())"
